=== borbelyadam/R41N5HWebXML/XML beadandó/DOMParseR41N5H/XMLSchemaR41N5H.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="cars">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="car" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Brand" type="xs:string"/>
                                        <xs:element name="Modell" type="xs:string"/>
                                        <xs:element name="Produced" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="PlateNo" type="xs:string"/>
                                    <xs:attribute name="CID" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="CreditCards">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="CreditCard" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Type" type="xs:string"/>
                                        <xs:element name="Expire" type="LejaratiDatum"/>
                                        <xs:element name="Bank" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="CardNO" type="Cardtip"/>
                                    <xs:attribute name="CID" type="cidnum"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Costumers">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Costumer" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="email" type="xs:string"/>
                                        <xs:element name="passwd" type="xs:string"/>
                                        <xs:element name="UserName" type="xs:string"/>
                                        <xs:element name="Name">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="FirstName" type="xs:string"/>
                                                    <xs:element name="LastName" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Address">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="country" type="xs:string"/>
                                                    <xs:element name="County" type="xs:string"/>
                                                    <xs:element name="Zip" type="xs:integer"/>
                                                    <xs:element name="City" type="xs:string"/>
                                                    <xs:element name="Street" type="xs:string"/>
                                                    <xs:element name="StreetNo" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="CID" type="xs:integer"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Requests">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Request" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ShipMode" type="xs:string"/>
                                        <xs:element name="Price" type="xs:string"/>
                                        <xs:element name="ShipPrice" type="xs:string"/>
                                        <xs:element name="PayMode" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="ReqID" type="xs:integer"/>
                                    <xs:attribute name="CID" type="xs:integer"/>
                                    <xs:attribute name="PID" type="xs:integer"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Rates">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Rate" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Who" type="xs:string"/>
                                        <xs:element name="Ratee" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="RiD" type="xs:string"/>
                                    <xs:attribute name="PID" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Products">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Product" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Price" type="xs:integer"/>
                                        <xs:element name="Descreption" type="xs:string"/>
                                        <xs:element name="Name" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="Pid" type="xs:integer"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="CarTypes">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="CarType" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Produced" type="xs:integer"/>
                                        <xs:element name="Brand" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="CTID" type="xs:integer"/>
                                    <xs:attribute name="PID" type="xs:integer"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Pictures">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Picture" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Title" type="xs:string"/>
                                        <xs:element name="filePath" type="xs:string"/>
                                        <xs:element name="Caption" type="xs:string"/>
                                    </xs:sequence>
                                    <xs:attribute name="PicID" type="xs:integer"/>
                                    <xs:attribute name="PID" type="xs:integer"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Orders">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Order" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="PartName" type="xs:string"/>
                                        <xs:element name="CarTypok" type="xs:string"/>
                                        <xs:element name="Price" type="xs:integer"/>
                                    </xs:sequence>
                                    <xs:attribute name="OrID" type="xs:integer"/>
                                    <xs:attribute name="PID" type="xs:integer"/>
                                    <xs:attribute name="SiD" type="xs:integer"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Suppliers">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Supplier" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Name" type="xs:string"/>
                                        <xs:element name="Address">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="country" type="xs:string"/>
                                                    <xs:element name="County" type="xs:string"/>
                                                    <xs:element name="Zip" type="xs:string"/>
                                                    <xs:element name="City" type="xs:string"/>
                                                    <xs:element name="Street" type="xs:string"/>
                                                    <xs:element name="StreetNo" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="SID" type="xs:integer"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        <xs:key name="Car_Key">
            <xs:selector xpath="car"/>
            <xs:field xpath="@PlateNo"/>
        </xs:key>
        <xs:key name="CreditCard_Key">
            <xs:selector xpath="CreditCard"/>
            <xs:field xpath="@CardNO"/>
        </xs:key>
        <xs:key name="Costumer_Key">
            <xs:selector xpath="Costumer"/>
            <xs:field xpath="@CID"/>
        </xs:key>
        <xs:key name="Request_Key">
            <xs:selector xpath="Request"/>
            <xs:field xpath="@ReqID"/>
        </xs:key>
        <xs:key name="Rate_key">
            <xs:selector xpath="Rate"/>
            <xs:field xpath="@RiD"/>
        </xs:key>
        <xs:key name="Product_key">
            <xs:selector xpath="Product"/>
            <xs:field xpath="@PiD"/>
        </xs:key>
        <xs:key name="CarTypes_key">
            <xs:selector xpath="CarType"/>
            <xs:field xpath="@CTID"/>
        </xs:key>
        <xs:key name="Picture_key">
            <xs:selector xpath="Picture"/>
            <xs:field xpath="@PicID"/>
        </xs:key>
        <xs:key name="Order_key">
            <xs:selector xpath="Order"/>
            <xs:field xpath="@OrID"/>
        </xs:key>
        <xs:key name="Supplier_key">
            <xs:selector xpath="Supplier"/>
            <xs:field xpath="@SID"/>
        </xs:key>
        <xs:keyref name="Fkey_Car_Costumer" refer="Costumer_Key">
            <xs:selector xpath="car"/>
            <xs:field xpath="@CID"/>
        </xs:keyref>
        <xs:keyref name="Fkey_CreditCard_Costumer" refer="Costumer_Key">
            <xs:selector xpath="CreditCard"/>
            <xs:field xpath="@CID"/>
        </xs:keyref>
        <xs:keyref name="Fkey_Request_Costumer" refer="Costumer_Key">
            <xs:selector xpath="Request"/>
            <xs:field xpath="@CID"/>
        </xs:keyref>
        <xs:keyref name="Fkey_Request_Product" refer="Product_key">
            <xs:selector xpath="Request"/>
            <xs:field xpath="@PID"/>
        </xs:keyref>
        <xs:keyref name="Fkey_CarType_Product" refer="Product_key">
            <xs:selector xpath="CarType"/>
            <xs:field xpath="@PID"/>
        </xs:keyref>
        <xs:keyref name="Fkey_Rates_Product" refer="Product_key">
            <xs:selector xpath="Rate"/>
            <xs:field xpath="@PID"/>
        </xs:keyref>
        <xs:keyref name="Fkey_Product_Order" refer="Product_key">
            <xs:selector xpath="Order"/>
            <xs:field xpath="@PID"/>
        </xs:keyref>
        <xs:keyref name="Fkey_Picture_Product" refer="Product_key">
            <xs:selector xpath="Picture"/>
            <xs:field xpath="@PID"/>
        </xs:keyref>
        <xs:keyref name="Fkey_Order_Supplier" refer="Supplier_key">
            <xs:selector xpath="Order"/>
            <xs:field xpath="@SID"/>
        </xs:keyref>
    </xs:element>
    <xs:simpleType name="LejaratiDatum">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{1}[0-9]{1}-[0-9]{1}[0-9]{1}" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Cardtip">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{11}" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="cidnum">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{3}" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== borbelyadam/R41N5HWebXML/XML beadandó_modified/DOMParseR41N5H/XMLR41N5HModify.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaR41N5H.xsd">
    <cars>
        <car CID="001" PlateNo="asd123">
            <Brand>Aygo</Brand>
            <Modell>Toyota</Modell>
            <Produced>2010</Produced>
        </car>
        <car CID="002" PlateNo="cfg456">
            <Brand>Aygo</Brand>
            <Modell>Toyota</Modell>
            <Produced>2010</Produced>
        </car>
        <car CID="003" PlateNo="mnb932">
            <Brand>Swift</Brand>
            <Modell>Suzuki</Modell>
            <Produced>2008</Produced>
        </car>
        <car CID="004" PlateNo="kli673">
            <Brand>E60</Brand>
            <Modell>BMW</Modell>
            <Produced>2015</Produced>
        </car>
    </cars>
    <CreditCards>
        <CreditCard CID="001" CardNO="12344567893">
            <Type>Visa</Type>
            <Expire>24-10</Expire>
            <Bank>K and H</Bank>
        </CreditCard>
        <CreditCard CID="002" CardNO="45612378934">
            <Type>Amex</Type>
            <Expire>23-07</Expire>
            <Bank>OTP</Bank>
        </CreditCard>
        <CreditCard CID="003" CardNO="98712345634">
            <Type>Visa</Type>
            <Expire>23-08</Expire>
            <Bank>ABG</Bank>
        </CreditCard>
        <CreditCard CID="004" CardNO="12344567893">
            <Type>Visa</Type>
            <Expire>24-10</Expire>
            <Bank>CA</Bank>
        </CreditCard>
    </CreditCards>
    <Costumers>
        <Costumer CID="001">
            <email>dean@gmail.com</email>
            <passwd>hangpass</passwd>
            <UserName>Dean</UserName>
            <Name>
                <FirstName>Dean</FirstName>
                <LastName>Winchester</LastName>
            </Name>
            <Address>
                <country>Magyarorszag</country>
                <County>BAZ</County>
                <Zip>3530</Zip>
                <City>Miskolc</City>
                <Street>Elet utca</Street>
                <StreetNo>5</StreetNo>
            </Address>
        </Costumer>
        <Costumer CID="002">
            <email>alal1@yahoo.com</email>
            <passwd>hunpass</passwd>
            <UserName>Belika</UserName>
            <Name>
                <FirstName>Bela</FirstName>
                <LastName>Nagy</LastName>
            </Name>
            <Address>
                <country>Magyarorszag</country>
                <County>BAZ</County>
                <Zip>3530</Zip>
                <City>Miskolc</City>
                <Street>Boldog utca</Street>
                <StreetNo>90</StreetNo>
            </Address>
        </Costumer>
        <Costumer CID="003">
            <email>hamar1@freemail.hu</email>
            <passwd>alapass</passwd>
            <UserName>UgraBug</UserName>
            <Name>
                <FirstName>Alfred</FirstName>
                <LastName>Gonzalez</LastName>
            </Name>
            <Address>
                <country>Magyarorszag</country>
                <County>BAZ</County>
                <Zip>3530</Zip>
                <City>Miskolc</City>
                <Street>Hatalom utca</Street>
                <StreetNo>10</StreetNo>
            </Address>
        </Costumer>
        <Costumer CID="004">
            <email>nGerg@gmail.com</email>
            <passwd>nempass</passwd>
            <UserName>Geri78</UserName>
            <Name>
                <FirstName>Gergely</FirstName>
                <LastName>Németh</LastName>
            </Name>
            <Address>
                <country>Magyarorszag</country>
                <County>Pest Megye</County>
                <Zip>1082</Zip>
                <City>Budapest VIII</City>
                <Street>Hock Jánós út</Street>
                <StreetNo>2</StreetNo>
            </Address>
        </Costumer>
    </Costumers>
    <Requests>
        <Request CID="001" PID="001" ReqID="001">
            <ShipMode>Személyes</ShipMode>
            <Price>10000</Price>
            <ShipPrice>0</ShipPrice>
            <PayMode>KP</PayMode>
        </Request>
        <Request CID="004" PID="003" ReqID="002">
            <ShipMode>Futár</ShipMode>
            <Price>12000</Price>
            <ShipPrice>10</ShipPrice>
            <PayMode>BK</PayMode>
        </Request>
        <Request CID="002" PID="002" ReqID="003">
            <ShipMode>Posta</ShipMode>
            <Price>33</Price>
            <ShipPrice>2</ShipPrice>
            <PayMode>UV</PayMode>
        </Request>
    </Requests>
    <Rates>
        <Rate PID="001" RiD="001">
            <Who>Belika</Who>
            <Ratee>1</Ratee>
        </Rate>
        <Rate PID="003" RiD="002">
            <Who>Dean</Who>
            <Ratee>4</Ratee>
        </Rate>
        <Rate PID="002" RiD="003">
            <Who>UgraBug</Who>
            <Ratee>6</Ratee>
        </Rate>
    </Rates>
    <Products>
        <Product Pid="001">
            <Price>12000</Price>
            <Descreption>Komplett motor blokk</Descreption>
            <Name>Motor</Name>
        </Product>
        <Product Pid="002">
            <Price>500</Price>
            <Descreption>Vezérműszíj</Descreption>
            <Name>Szíj</Name>
        </Product>
        <Product Pid="003">
            <Price>6000</Price>
            <Descreption>Toronycsapágy</Descreption>
            <Name>csapágy</Name>
        </Product>
        <Product Pid="004">
            <Price>3000</Price>
            <Descreption>Jobb normál saru</Descreption>
            <Name>Akkumlátor</Name>
        </Product>
    </Products>
    <CarTypes>
        <CarType CTID="001" PID="001">
            <Produced>2014</Produced>
            <Brand>Toyota</Brand>
        </CarType>
        <CarType CTID="002" PID="002">
            <Produced>2008</Produced>
            <Brand>Toyota</Brand>
        </CarType>
        <CarType CTID="003" PID="003">
            <Produced>2009</Produced>
            <Brand>Suzuki</Brand>
        </CarType>
        <CarType CTID="004" PID="004">
            <Produced>2011</Produced>
            <Brand>BMW</Brand>
        </CarType>
    </CarTypes>
    <Pictures>
        <Picture PID="001" PicID="001">
            <Title>Enng.jpg</Title>
            <filePath>/home/pic/toyota</filePath>
            <Caption>Toy</Caption>
        </Picture>
        <Picture PID="002" PicID="002">
            <Title>Enng.jpg</Title>
            <filePath>/home/pic/Toyota</filePath>
            <Caption>Toyota</Caption>
        </Picture>
        <Picture PID="003" PicID="003">
            <Title>Enng.jpg</Title>
            <filePath>/home/pic/suz</filePath>
            <Caption>Suz</Caption>
        </Picture>
        <Picture PID="004" PicID="004">
            <Title>Enng.jpg</Title>
            <filePath>/home/pic/BMW</filePath>
            <Caption>BMW</Caption>
        </Picture>
    </Pictures>
    <Orders>
        <Order OrID="001" PID="001" SiD="001">
            <PartName>Kipufogócső</PartName>
            <CarTypok>Toyota</CarTypok>
            <Price>3</Price>
        </Order>
        <Order OrID="002" PID="002" SiD="002">
            <PartName>Komplett motor</PartName>
            <CarTypok>Ferrari</CarTypok>
            <Price>9000</Price>
        </Order>
        <Order OrID="003" PID="003" SiD="003">
            <PartName>Stabilizátor</PartName>
            <CarTypok>Audi</CarTypok>
            <Price>15</Price>
        </Order>
        <Order OrID="004" PID="004" SiD="004">
            <PartName>Féktárcsa</PartName>
            <CarTypok>Chevrolet</CarTypok>
            <Price>6</Price>
        </Order>
    </Orders>
    <Suppliers>
        <Supplier SID="001">
            <Name>BOSCH</Name>
            <Address>
                <country>Magyarorszag</country>
                <County>BAZ</County>
                <Zip>3526</Zip>
                <City>Miskolc</City>
                <Street>Robert Bosch Park</Street>
                <StreetNo>1</StreetNo>
            </Address>
        </Supplier>
        <Supplier SID="002">
            <Name>AUTOMOTIVE</Name>
            <Address>
                <country>England</country>
                <County>AB10</County>
                <Zip>1JB</Zip>
                <City>Aberdeen</City>
                <Street>Albyn Place</Street>
                <StreetNo>&gt;37</StreetNo>
            </Address>
        </Supplier>
        <Supplier SID="003">
            <Name>SEMA</Name>
            <Address>
                <country>Germany</country>
                <County>D77</County>
                <Zip>87499</Zip>
                <City>Wildpoldsried</City>
                <Street>Dorfmuehlstr</Street>
                <StreetNo>&gt;11</StreetNo>
            </Address>
        </Supplier>
    </Suppliers>
</root>
